"""add external_id to products

Revision ID: aa68d8059a93
Revises: 0001
Create Date: 2026-06-13 08:31:38.574894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa68d8059a93'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_products_source_external_id', 'products', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_source_external_id', 'products', type_='unique')
    op.drop_column('products', 'external_id')
    # ### end Alembic commands ###
